# ================================
# BT NAVIGATOR
# ================================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    local_frame: odom
    robot_base_frame: base_link
    odom_topic: /odom
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    default_nav_to_pose_bt_xml: "REPLACED_AT_LAUNCH"
    default_nav_through_poses_bt_xml: "REPLACED_AT_LAUNCH"

behavior_server:
  ros__parameters:
    use_sim_time: true
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link # Asegúrate que coincida con tu URDF
    transform_tolerance: 0.1
    
    # Solo habilitamos comportamientos que un coche puede hacer
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    
    spin:
      plugin: "nav2_behaviors/Spin"

    backup:
      plugin: "nav2_behaviors/BackUp"
    
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    
    wait:
      plugin: "nav2_behaviors/Wait"

    # LIMITES DE ACELERACIÓN (Esto quita el mensaje de INFO que viste)
    # Ajustados para un robot tipo coche de tamaño medio
    max_acceleration: 0.2     # m/s^2 (suave para no patinar en Gazebo)
    max_deceleration: 0.5     # m/s^2
    max_angular_acceleration: 0.1 # rad/s^2
    max_angular_deceleration: 0.1 # rad/s^2

    # Parámetros específicos de las maniobras
    simulate_ahead_time: 2.0
  
# ================================
# PLANNER (Hybrid A* con reversa)
# ================================
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      optimizer_costmap_weight: 15.0

      tolerance: 0.5
      allow_unknown: true
      max_planning_time: 2.0
      max_iterations: 1000000

      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 1.645448267      # RADIO DE GIRO
      angle_quantization_bins: 72

      allow_reversing: true      # PERMITIR REVERSA
      reverse_penalty: 0.5
      change_penalty: 1.0
      non_straight_penalty: 0.3
      cost_penalty: 2.0

      smooth_path: true
      debug_visualizations: false

# ================================
# CONTROLLER (MPPI Ackermann)
# ================================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    odom_topic: /odom
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    current_goal_checker: "general_goal_checker"
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      use_cuda: false

      motion_model: "Ackermann"
      time_steps: 20
      model_dt: 0.1
      batch_size: 800
      iteration_count: 1

      vx_max: 3.0
      vx_min: -3.0          # REVERSA
      wz_max: 2.0       # VELOCIDAD DE GIRO
      wz_min: -2.0
      vy_max: 0.0       # NO TOCAR

      vx_std: 0.1
      wz_std: 0.6

      AckermannConstraints:
        min_turning_r: 1.645448267  # RADIO DE GIRO

      critics:
        [
          "ConstraintCritic",
          "CostCritic",
          "GoalCritic",
          "GoalAngleCritic",
          "PathAlignCritic",
          "PathFollowCritic",
          "PathAngleCritic",
          "PreferForwardCritic"
        ]

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0   # BAJO

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 8.0
        critical_cost: 250.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 3.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 14.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.5
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        offset_from_furthest: 5
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

# ================================
# LOCAL COSTMAP (rolling)
# ================================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.1
      transform_tolerance: 1.0
      footprint: "[[1.19,0.46],[1.19,-0.46],[-0.25,-0.46],[-0.25,0.46]]"
      footprint_padding: 0.15
      plugins: ["voxel_layer", "inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 3.0
        cost_scaling_factor: 1.5
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 1.60
        min_obstacle_height: 0.11
        mark_threshold: 0
        unknown_threshold: 15
        combination_method: 1
        observation_sources: lidar
        lidar:
          topic: /lidar/points
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      always_send_full_costmap: true

# ================================
# GLOBAL COSTMAP (rolling, GPS)
# ================================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[1.19,0.46],[1.19,-0.46],[-0.25,-0.46],[-0.25,0.46]]"
      footprint_padding: 0.15
      rolling_window: true
      width: 40
      height: 40
      resolution: 0.05
      transform_tolerance: 1.0
      track_unknown_space: true
      use_maximum_static_value: true
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: lidar
        lidar:
          topic: /lidar/points
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.2
        cost_scaling_factor: 2.0
      always_send_full_costmap: true

# ================================
# VELOCITY SMOOTHER
# ================================
velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 30.0
    feedback: "CLOSED_LOOP"
    odom_topic: /odom

    max_velocity: [3.0, 0.0, 1.0]
    min_velocity: [-3.0, 0.0, -1.0]

    max_accel: [2.0, 0.0, 1.5]
    max_decel: [-3.0, 0.0, -1.8]

    deadband_velocity: [0.01, 0.0, 0.0]
    velocity_timeout: 0.5

# ================================
# BEHAVIOR SERVER (no Spin)
# ================================
behavior_server:
  ros__parameters:
    use_sim_time: true
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["backup", "drive_on_heading", "assisted_teleop", "wait"]
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0

# ================================
# LIFECYCLE
# ================================
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - bt_navigator
      - behavior_server
