# ================================
# BT NAVIGATOR
# ================================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    local_frame: odom
    robot_base_frame: base_footprint
    odom_topic: /odometry/local
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    default_nav_to_pose_bt_xml: "REPLACED_AT_LAUNCH"
    default_nav_through_poses_bt_xml: "REPLACED_AT_LAUNCH"

behavior_server:
  ros__parameters:
    use_sim_time: true
    local_frame: odom
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.1
    simulate_ahead_time: 3.0
    expansion_factor: 1.0
    
    behavior_plugins: [
      "backup",
      "drive_on_heading",
      "wait"
    ]

    backup:
      plugin: "nav2_behaviors/BackUp"
      simulate_ahead_time: 2.0
      stall_timeout: 3.0
    
    drive_on_heading:
      simulate_ahead_time: 2.0
      plugin: "nav2_behaviors/DriveOnHeading"
    
    wait:
      plugin: "nav2_behaviors/Wait"

    # LIMITES DE ACELERACIÓN (Esto quita el mensaje de INFO que viste)
    # Ajustados para un robot tipo coche de tamaño medio
    max_acceleration: 0.2     # m/s^2 (suave para no patinar en Gazebo)
    max_deceleration: 0.5     # m/s^2
    max_angular_acceleration: 0.1 # rad/s^2
    max_angular_deceleration: 0.1 # rad/s^2

  
# ================================
# PLANNER (Hybrid A* con reversa)
# ================================
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    robot_base_frame: base_footprint
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      optimizer_costmap_weight: 15.0

      tolerance: 0.5
      allow_unknown: true
      max_planning_time: 2.0
      max_iterations: 1000000

      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 1.75      # RADIO DE GIRO
      angle_quantization_bins: 72

      allow_reversing: true      # PERMITIR REVERSA
      reverse_penalty: 4.0
      change_penalty: 1.0
      non_straight_penalty: 2.5
      cost_penalty: 2.0
      cost_travel_multiplier: 1.0  # castigo por distancia extra

      smooth_path: true
      debug_visualizations: false

# ================================
# CONTROLLER (MPPI Ackermann)
# ================================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    odom_topic: /odometry/local
    robot_base_frame: base_footprint
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    current_goal_checker: "general_goal_checker"
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.5
      yaw_goal_tolerance: 1.0

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      use_cuda: false

      motion_model: "Ackermann"
      time_steps: 50
      model_dt: 0.1
      batch_size: 800
      iteration_count: 1
      angle_quantization_bins: 72
      noise_stddev: [0.25, 0.0, 0.2] # Baja el último valor si zigzaguea mucho
      noise_filter_tau: 0.35

      # VELOCIDADES
      regulated_linear_velocity_scaling_factor: 0.8 # mas alto -> mas frena en curvas
      vx_max: 0.5
      vx_min: -0.3         # REVERSA
      min_theta_velocity: 0.0        # VELOCIDAD DE GIRO
      max_theta_velocity: 0.35
      wz_max: 0.28571  # velocidad angular
      wz_min: -0.28571
      max_accel: 0.4
      max_decel: -1.0
      vy_max: 0.0       # NO TOCAR

      vx_std: 0.2
      wz_std: 0.4

      AckermannConstraints:
        min_turning_r: 1.75  # RADIO DE GIRO

      critics:
        [
          "ConstraintCritic",
          "CostCritic",
          "GoalCritic",
          "GoalAngleCritic",
          "PathAlignCritic",
          "PathFollowCritic",
          "PathAngleCritic",
          "PreferForwardCritic",
          "ObstaclesCritic",
          "TwirlingCritic"
        ]

      TwirlingCritic:
        enabled: true
        cost_power: 1
        cost_weight: 1.0

      ConstraintCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0

      CostCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        critical_cost: 250.0
        consider_footprint: true
        collision_cost: 1000000.0
        near_goal_distance: 1.0
        trajectory_point_step: 2

      GoalCritic:
        enabled: true
        cost_power: 1
        cost_weight: 15.0
        threshold_to_consider: 1.5
        trajectory_point_step: 1

      GoalAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        threshold_to_consider: 0.5

      PreferForwardCritic:
        enabled: true
        cost_power: 1
        cost_weight: 5.0
        threshold_to_consider: 0.5

      PathAlignCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        max_path_occupancy_ratio: 0.05
        trajectory_point_step: 4
        threshold_to_consider: 0.7
        offset_from_furthest: 20
        use_path_orientations: false

      PathFollowCritic:
        enabled: true
        cost_power: 1
        cost_weight: 10.0
        offset_from_path: true
        offset_from_furthest: 25
        threshold_to_consider: 1.4

      PathAngleCritic:
        enabled: true
        cost_power: 1
        cost_weight: 2.0
        offset_from_furthest: 4
        threshold_to_consider: 0.5
        max_angle_to_furthest: 1.0
        mode: 0

      ObstaclesCritic:
        enabled: true
        cost_weight: 6.0
        consider_footprint: true

# ================================
# LOCAL COSTMAP (rolling)
# ================================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.1
      transform_tolerance: 1.0
      footprint: "[[1.19,0.46],[1.19,-0.46],[-0.25,-0.46],[-0.25,0.46]]"
      footprint_padding: 0.0
      plugins: ["voxel_layer", "inflation_layer"]
      track_unknown_space: false

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.2
        cost_scaling_factor: 3.0
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 1.60
        min_obstacle_height: 0.11
        mark_threshold: 0
        unknown_threshold: 15
        combination_method: 1
        observation_sources: lidar
        lidar:
          topic: /scan_3d
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      always_send_full_costmap: true

# ================================
# GLOBAL COSTMAP (rolling, GPS)
# ================================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      footprint: "[[1.19,0.46],[1.19,-0.46],[-0.25,-0.46],[-0.25,0.46]]"
      footprint_padding: 0.0
      rolling_window: true
      width: 40
      height: 40
      resolution: 0.1
      transform_tolerance: 1.0
      track_unknown_space: false
      use_maximum_static_value: true
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: lidar
        lidar:
          topic: /scan_3d
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          obstacle_max_range: 10.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 10.0
      always_send_full_costmap: true

# ================================
# VELOCITY SMOOTHER
# ================================
velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 15.0
    feedback: "CLOSED_LOOP"
    odom_topic: /odometry/local
    robot_base_frame: base_footprint

    max_velocity: [1.0, 0.0, 1.0]
    min_velocity: [-0.7, 0.0, -1.0]

    max_accel: [1.0, 0.0, 1.0]
    max_decel: [-2.0, 0.0, -1.0]

    # si la velocidad calculada es menor a esto se envía 0 a los motores
    deadband_velocity: [0.05, 0.0, 0.05]
    velocity_timeout: 0.5

# ================================
# LIFECYCLE
# ================================
lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - bt_navigator
      - behavior_server
      - waypoint_follower
      - collision_monitor
