# ================================
# BT NAVIGATOR
# ================================
bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /odom
    navigators: ["navigate_to_pose"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"

# ================================
# PLANNER (Hybrid A* con reversa)
# ================================
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"

      tolerance: 0.5
      allow_unknown: true
      max_planning_time: 2.0

      motion_model_for_search: "REEDS_SHEPP"
      minimum_turning_radius: 0.9370394869      # AJUSTAR A TU VEH√çCULO
      angle_quantization_bins: 72

      reverse_penalty: 0.5
      change_penalty: 1.0
      non_straight_penalty: 0.8
      cost_penalty: 1.2

      smooth_path: true
      debug_visualizations: false

# ================================
# CONTROLLER (MPPI Ackermann)
# ================================
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0
    odom_topic: /odom
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    current_goal_checker: "general_goal_checker"
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"

      motion_model: "Ackermann"
      time_steps: 50
      model_dt: 0.1
      batch_size: 2000
      iteration_count: 1

      vx_max: 3.0
      vx_min: -3.0          # REVERSA
      vy_max: 0.0
      wz_max: 10.0
      wz_min: -10.0

      vx_std: 0.1
      wz_std: 0.6

      AckermannConstraints:
        min_turning_r: 0.9370394869  # Permite giros mas cerrados

      critics:
        [
          "ConstraintCritic",
          "CostCritic",
          "GoalCritic"
        ]

      ConstraintCritic:
        enabled: true
        cost_weight: 2.0   # BAJO

      CostCritic:
        enabled: true
        cost_weight: 2.0

      GoalCritic:
        enabled: true
        cost_weight: 3.0

# ================================
# LOCAL COSTMAP (rolling)
# ================================
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_footprint
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.1
      transform_tolerance: 0.2
      footprint: "[[0.8,0.5],[0.8,-0.5],[-0.8,-0.5],[-0.8,0.5]]"
      plugins: ["voxel_layer", "inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.2
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 1.60
        min_obstacle_height: 0.11
        mark_threshold: 0
        unknown_threshold: 15
        combination_method: 1
        observation_sources: lidar
        lidar:
          topic: /lidar/points
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      always_send_full_costmap: true

# ================================
# GLOBAL COSTMAP (rolling, GPS)
# ================================
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_footprint
      footprint: "[[0.8,0.5],[0.8,-0.5],[-0.8,-0.5],[-0.8,0.5]]"
      rolling_window: true
      width: 40
      height: 40
      resolution: 0.1
      transform_tolerance: 0.2
      track_unknown_space: true
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: lidar
        lidar:
          topic: /lidar/points
          max_obstacle_height: 1.60
          min_obstacle_height: 0.11
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 20.0
          raytrace_min_range: 0.0
          obstacle_max_range: 20.0
          obstacle_min_range: 0.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.2
      always_send_full_costmap: true

# ================================
# VELOCITY SMOOTHER
# ================================
velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 30.0
    feedback: "CLOSED_LOOP"
    odom_topic: /odom

    max_velocity: [3.0, 0.0, 1.0]
    min_velocity: [-3.0, 0.0, -1.0]

    max_accel: [2.0, 0.0, 1.5]
    max_decel: [-3.0, 0.0, -1.8]

    deadband_velocity: [0.01, 0.0, 0.0]
    velocity_timeout: 0.5

# ================================
# LIFECYCLE
# ================================
lifecycle_manager_navigation:
  ros__parameters:
    autostart: true
    node_names:
      - planner_server
      - controller_server
      - bt_navigator
