pointcloud_to_laserscan:
  ros__parameters:
    use_sim_time: true
    target_frame: base_footprint
    transform_tolerance: 0.1
    min_height: 0.11
    max_height: 1.60
    angle_min: -1.57079632679
    angle_max: 1.57079632679
    angle_increment: 0.00872664626
    scan_time: 0.1
    range_min: 0.2
    range_max: 20.0
    use_inf: true
    inf_epsilon: 1.0